
<!DOCTYPE html>
<html lang="bg">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Флиртчето - Премиум абонамент</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f5f5f5;
            margin: 0;
            padding: 0;
        }
        .header {
            background-color: #ff1a75;
            padding: 20px;
            text-align: center;
            color: white;
        }
        .container {
            max-width: 800px;
            margin: 40px auto;
            background: white;
            padding: 20px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
        }
        .premium-info {
            text-align: center;
            margin-bottom: 30px;
        }
        .premium-info h2 {
            color: #ff1a75;
            font-size: 24px;
        }
        .premium-info p {
            font-size: 18px;
            color: #333;
        }
        .premium-button {
            padding: 15px 30px;
            font-size: 18px;
            background-color: #ff4d88;
            color: white;
            border: none;
            border-radius: 8px;
            cursor: pointer;
            margin-top: 20px;
        }
        .premium-button:hover {
            background-color: #ff3399;
        }
        .footer {
            text-align: center;
            padding: 20px;
            background-color: #ff1a75;
            color: white;
            position: fixed;
            width: 100%;
            bottom: 0;
        }
    </style>
</head>
<body>

    <div class="header">
        <h1>Добре дошли в Флиртчето</h1>
    </div>

    <div class="container">
        <div class="premium-info">
            <h2>Станете Премиум Потребител</h2>
            <p>Абонирайте се за нашия премиум абонамент и получите неограничени харесвания, игри за флирт, по-добра видимост и много други ексклузивни функции!</p>
        </div>

        <div class="pricing">
            <h3>Месечен абонамент</h3>
            <p>10 лв. на месец</p>
        </div>

        <!-- PayPal Button -->
        <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
            <input type="hidden" name="cmd" value="_xclick">
            <input type="hidden" name="business" value="your_paypal_email@example.com"> <!-- Въведи своя PayPal имейл -->
            <input type="hidden" name="item_name" value="Флиртчето Премиум Абонамент">
            <input type="hidden" name="amount" value="10.00"> <!-- Цена за месечен абонамент -->
            <input type="hidden" name="currency_code" value="BGN">
            <input type="hidden" name="return" value="http://your-website.com/success"> <!-- URL за успех -->
            <input type="hidden" name="cancel_return" value="http://your-website.com/cancel"> <!-- URL за неуспех -->
            <button type="submit" class="premium-button">Абонирай се с PayPal</button>
        </form>
    </div>

    <div class="footer">
        <p>&copy; 2025 Флиртчето. Всички права запазени.</p>
    </div>

</body>
</html>
